### ISSUE TITLE
Visual representation of previous bed net distributions

### ISSUE THREAD

**Issue by benjamin-heasly** [cims-bioko/cims-tablet#111]
Currently, the tablet application "remembers" which households have had bed nets already distributed, but only as long as the bed net forms remain on the tablet.  Once the forms are pushed to the server, the tablet application "forgets" which houses have already had bed nets distributed.

We would like all tablets to visually represent which houses have already had bed nets distributed, before or after the forms have been sent to the server, and even if the forms were never present on a given tablet.

---

This would be a new kind of functionality on the tablet because it would require the tablets and server to "remember" information that is not part of the OpenHDS demographic data model.

So we must design this feature.

**Comment by batkinson** [comment]
Closing since its relevance is diminished to recent application versions. For one, the functionality for remembering which houses were given bed nets was removed. This hack was not only conceptually incomplete since it only tracked things local to the tablet, it actually caused considerable data collection problems. The fact that the form button was disabled and there wasn't an easy way to identify and edit a form once created meant that surveyors ended up getting "locked out" of the tablet for a location if they made a mistake. This lead to them doing tablet swaps to enter a corrected form, but they would end up submitting both since the original was also a completed form.

Since this time, the tablet shows created forms in the hierarchy where the form was created from. This allows them to easily identify and edit the form. This also allows them to see if they have created a spray form for the location, so using the custom tracking scheme provides less value, especially considering it is reset when resyncing with the server. Lastly, the fact that this didn't propagate to the other tablets causes a good amount of confusion. In the end, it prevents users from building an intuition for what is going on when they perform these operations. As of version 3.0 of the cims-tablet application, there is an alternative for the hack used to store this state information. The remaining entities, which have been reduced to location, individual, and hierarchy, have an attributes column that allows for arbitrary information stored as JSON. This information is propagated to the tablets, so it is possible to build a much more robust tracking solution in this style if it was necessary (it's not).
