### ISSUE TITLE
Don't allow duplicate bed net forms for a household

### ISSUE THREAD

**Issue by benjamin-heasly** [cims-bioko/cims-tablet#113]
Currently, it is possible to fill out multiple bed net distribution forms for a single household.  The tablet application should "remember" which households already have bed net forms, and disable additional bed net forms for that household.

**Comment by batkinson** [comment]
I'm closing this, since while it's less than perfect, there is working behavior attempting to address this in the application. When a bednet form is completed, the button is disabled. Note that it's still possible to complete a previously incomplete form as well (which is why's it not perfect). It is also possible for another tablet to complete a bednet form for the same location as well, which is essentially what #111 is attempting to address.
