### ISSUE TITLE
Why are there two separate local databases?

### ISSUE THREAD

**Issue by wolfe-lienhardt** [cims-bioko/cims-tablet#12]
Currently OpenHDSProvider uses a database named openhds.db which stores demographic data and fieldworker information. DatabaseAdapter uses a database named entityData which holds form and supervisor data.

Why are there two?
Why is fieldworker and supervisor data stored separately?
Why is fieldworker data stored with demographic data?

**Comment by batkinson** [comment]
I'm closing this since it's not necessarily something to "fix". At the time, data was delivered to the application differently than it is now. Specifically, the database was created and subsequently populated by fetching XML from the server and parsing it. The assumption was that the database was owned and wholly managed by the mobile application.

Due to the growing data sizes and varying storage performance between tablets, users experienced significant performance issues that resulted in avoidance of regular data synchronization. This lead to a number of data quality and work flow issues that required significant human effort to cleanup once field activities were complete.

To address this, an alternative interim approach was adopted to handle the bulk synchronization: the sqlite database is constructed and populated once on the server and delivered as a single file to the tablets. This addressed multiple issues at once. Tablets no longer needed to to download XML that was significantly larger than the database it would create (xml sizes were approaching 1GB, while the resulting database was ~250MB). It also meant that the difference in storage speeds could be avoided since no parsing or database manipulation was required to update the data; the database could be updated by updating a single file system directory entry and reloading the content provider.

Once this scheme was adopted, the ownership of the database changed slightly. Now, there is definitely more of a case to be made for at least two independent data sources:

- Shared demographic information from the shared openhds database
- Tablet-local information that is independent from the shared demographic information

This second type of information might include references to demographic entities that the user would not want to lose across synchronization. This is similar to, but not the same as the behavior described in #111. In contrast to the behavior described in #111, this allows users to keep information across synchronizations on the same tablet, but would not allow sharing across tablets.

Given the current direction, merging the two databases is not appropriate. However, the way the non-shared database is used is likely to be changed and refined.
