### ISSUE TITLE
Support consuming edited forms from the field worker portal

### ISSUE THREAD

**Issue by andrew-d-taylor** [cims-bioko/cims-tablet#123]
Currently, changes to a saved form from the field worker portal does not persist the saved form data to the local tablet database. This makes the user interface unable to reflect the changes made to an edited form. While the data from the edited form will take effect after syncing with the server, it is confusing to the user when the tablet UI is not updated immediately.

This will be a design issue first, as the structure of the application does not immediately lend itself to this new type of form consumption.

_NOTE: This issue was originally written to include both field worker and supervisor portals. However, due to the significant differences in difficulty of implementing supervisor support they have been split._

**Comment by batkinson** [comment]
Closing since this the relevance has changed significantly with recent versions of the application.

The concept of a form-binding (which is identifiable from the form instance) was introduced laying the foundation for this type of functionality. However, there are more conceptual problems that prevent this from being a useful feature. For one, re-consuming a form only works conceptually if the consumption operation is idempotent. Ultimately, attempting to model creation and maintenance of database entities using ODK Collect is too leaky to be usable.
