### ISSUE TITLE
Unhappy/sad/evil path testing should be more rigorous.

### ISSUE THREAD

**Issue by wolfe-lienhardt** [cims-bioko/cims-tablet#74]
Is there any way for us to regularize or standardize our testing of the tablet application? 

Currently, the testing that is done is simply drilling through the basic functionality of the application after implementing changes to make sure new bugs or issues aren't created, however this isn't enough. We frequently run into problems outside (discovered by the field team) of the spectrum of what we tested that perhaps would have been handled if we were to standardize or implement some sort of protocol for testing the changes made to the application.

What is the best course of action?

**Comment by batkinson** [comment]
Closing this since it's an open question that won't find the individual who asked it. The solution to this is automated verification. However, like many applications not built with testing in mind retro-fitting test-ability is likely to be a time-consuming process at this point.

Currently, since most recent activity is coming from one individual this lack of consistency is not as much of a problem. Also there has been a lot of refactoring to improve the reliability and comprehensibility of the code. Fortunately, static typing and the refactoring tools have allowed for this despite lack of automated verification.

At this point, my approach to this would be to put all critical operations under a functional tests and then refactor them to more simple and testable code. At that point, writing unit tests for the simpler pieces should cover more than the very specific functional tests.

Functional tests are likely to be written in something like Appium or similar, integration and unit tests are probably instrumentation tests and normal junit tests.
